export default [
    {
        title: "Spider-man: Into the Spider-Verse",
        description: "Teen Miles Morales becomes Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.",
        duration: 117,
        types: ["animation","action","family"],
        actors: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
        directors: ["Bob Persichetti","Peter Ramsey","Rodney Rothman"],
        producers: ["Avi Arad","Amy Pascal","Phil Lord","Christopher Miller","Christina Steinberg"],
        date: "01/12/2018",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/pictures/18/11/13/11/42/1696141.jpg",
        language: "english",
        rating: 4.4,
        tags: ["animation","action","family","120"]
    },
    {
        title: "Avengers: Endgame",
        description: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        duration: 181,
        types: ["action","adventure","drama","sci-fi"],
        actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo","Chris Hemsworth","Scarlett Johansson","Jeremy Renner","Brie Larson","Paul Rudd"],
        directors: ["Anthony Russo","Joseph Russo"],
        producers: ["Kevin Feige"],
        date: "22/04/2019",
        image: "http://fr.web.img2.acsta.net/r_1920_1080/pictures/19/04/04/09/04/0472053.jpg",
        language: "english",
        rating: 4.2,
        tags: ["action","adventure","drama","sci-fi","999"]
    },
    {
        title: "Bridge to Terabithia",
        description: "A preteen's life turns upside down when he befriends the new girl in school and they imagine a whole new fantasy world to escape reality..",
        duration: 96,
        types: ["drama","family","fantasy"],
        actors: ["Josh Hutcherson","AnnaSophia Robb","Zooey Deschanel"],
        directors: ["Gabor Csupo"],
        producers: ["David L. Paterson","Lauren Levine","Hal Lieberman"],
        date: "28/03/2007",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/medias/nmedia/18/63/01/37/18742142.jpg",
        language: "english",
        rating: 3.2,
        tags: ["drama","family","fantasy","120"]
    },
    {
        title: "Finding Nemo",
        description: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
        duration: 100,
        types: ["animation","adventure","comedy"],
        actors: ["Albert Brooks","Ellen DeGeneres","Alexander Gould"],
        directors: ["Andrew Stanton","Lee Unkrich"],
        producers: ["David L. Paterson","Lauren Levine","Hal Lieberman"],
        date: "26/11/2003",
        image: "http://fr.web.img5.acsta.net/r_1920_1080/medias/nmedia/18/35/15/45/20258956.jpg",
        language: "english",
        rating: 3.2,
        tags: ["animation","adventure","comedy","120"]
    },
    {
        title: "Kingsman",
        description: "A spy organization recruits an unrefined, but promising street kid into the agency's ultra-competitive training program, just as a global threat emerges from a twisted tech genius.",
        duration: 124,
        types: ["action","adventure","comedy"],
        actors: ["Colin Firth","Taron Egerton","Samuel L. Jackson"],
        directors: ["Matthew Vaughn"],
        producers: ["Matthew Vaughn","David Reid","Adam Bohling"],
        date: "18/02/2015",
        image: "http://fr.web.img4.acsta.net/r_1920_1080/pictures/15/01/08/15/02/290347.jpg",
        language: "english",
        rating: 4.3,
        tags: ["action","adventure","comedy","120"]
    },
    {
        title: "Crazy, Stupid, Love",
        description: "A middle-aged husband's life changes dramatically when his wife asks him for a divorce. He seeks to rediscover his manhood with the help of a newfound friend, Jacob, learning to pick up girls at bars.",
        duration: 118,
        types: ["comedy","drama","romance"],
        actors: ["Steve Carell","Ryan Gosling","Julianne Moore","Emma Stone"],
        directors: ["Glenn Ficarra","John Requa"],
        producers: ["Steve Carell","Denise Di Novi"],
        date: "14/09/2011",
        image: "http://fr.web.img4.acsta.net/r_1920_1080/medias/nmedia/18/85/84/05/19808153.jpg",
        language: "english",
        rating: 3.9,
        tags: ["comedy","drama","romance","valentine's day","120"]
    },
    {
        title: "Frozen",
        description: "When the newly-crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.",
        duration: 102,
        types: ["animation","adventure","comedy"],
        actors: ["Kristen Bell","Idina Menzel","Jonathan Groff","Josh Gad","Santino Fontana"],
        directors: ["Chris Buck","Jennifer Lee"],
        producers: ["Peter Del Vecho"],
        date: "04/12/2013",
        image: "http://fr.web.img5.acsta.net/r_1920_1080/pictures/210/521/21052146_20131023144339759.jpg",
        language: "english",
        rating: 4.1,
        tags: ["animation","adventure","comedy","christmas","120"]
    },
    {
        title: "Frozen 2",
        description: "Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient, autumn-bound forest of an enchanted land. They set out to find the origin of Elsa's powers in order to save their kingdom.",
        duration: 104,
        types: ["animation","adventure","comedy"],
        actors: ["Kristen Bell","Idina Menzel","Jonathan Groff","Josh Gad"],
        directors: ["Chris Buck","Jennifer Lee"],
        producers: ["Peter Del Vecho"],
        date: "20/11/2019",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/pictures/19/10/25/15/08/5952325.jpg",
        language: "english",
        rating: 4.0,
        tags: ["animation","adventure","comedy","christmas","120"]
    },
    {
        title: "Annabelle",
        description: "A couple begins to experience terrifying supernatural occurrences involving a vintage doll shortly after their home is invaded by satanic cultists.",
        duration: 99,
        types: ["horror","mystery","thriller"],
        actors: ["Ward Horton","Annabelle Wallis","Alfre Woodard"],
        directors: ["John R. Leonetti"],
        producers: ["Peter Safran","James Wan"],
        date: "10/07/2014",
        image: "http://fr.web.img4.acsta.net/r_1920_1080/pictures/14/10/09/10/20/418344.jpg",
        language: "english",
        rating: 2.7,
        tags: ["horror","mystery","thriller","halloween","120"]
    },
    {
        title: "Ali Wong: Hard Knock Wife",
        description: "Comedian Ali Wong performs her live stand-up set at Toronto's Winter Garden Theatre.",
        duration: 64,
        types: ["comedy"],
        actors: ["Ali Wong"],
        directors: ["Jay Karas"],
        date: "13/05/2018",
        image: "https://m.media-amazon.com/images/M/MV5BMWVkZDNjZTMtMTY0Yi00OGQ0LTliMDEtMWMxYzljYzZlYTY3XkEyXkFqcGdeQXVyMTEzNjA2NzM@._V1_.jpg",
        language: "english",
        rating: 3.7,
        tags: ["comedy","60"]
    },
    {
        title: "Intouchables",
        description: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
        duration: 112,
        types: ["biography","comedy","drama"],
        actors: ["François Cluzet","Omar Sy","Anne Le Ny"],
        directors: ["Olivier Nakache","Éric Toledano"],
        producers: ["Nicolas Duval Adassovsky","Yann Zenou","Laurent Zeitoun"],
        date: "02/11/2011",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/medias/nmedia/18/82/69/17/19806656.jpg",
        language: "french",
        rating: 4.3,
        tags: ["biography","comedy","drama","120"]
    },
    {
        title: "Les Choristes",
        description: "The new teacher at a severely administered boys' boarding school works to positively affect the students' lives through music.",
        duration: 97,
        types: ["drama","music"],
        actors: ["Gérard Jugnot","François Berléand","Jean-Baptiste Maunier"],
        directors: ["Christophe Barratier"],
        producers: ["Arthur Cohn","Jacques Perrin","Gérard Jugnot"],
        date: "17/03/2004",
        image: "http://fr.web.img5.acsta.net/r_1920_1080/medias/nmedia/18/35/18/77/18373973.jpg",
        language: "french",
        rating: 3.6,
        tags: ["drama","music","120"]
    },
    {
        title: "The Sixth Sense",
        description: "A boy who communicates with spirits seeks the help of a disheartened child psychologist.",
        duration: 107,
        types: ["drama","mystery","thriller"],
        actors: ["Bruce Willis","Haley Joel Osment","Toni Collette"],
        directors: ["M. Night Shyamalan"],
        producers: ["Frank Marshall","Kathleen Kennedy","Barry Mendel"],
        date: "05/01/2000",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/medias/nmedia/18/66/15/77/19255607.jpg",
        language: "english",
        rating: 4.3,
        tags: ["drama","mystery","thriller","120"]
    },
    {
        title: "Inglorious Basterds",
        description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        duration: 153,
        types: ["adventure","drama","war"],
        actors: ["Christoph Waltz","Brad Pitt","Diane Kruger","Eli Roth"],
        directors: ["Quentin Tarantino"],
        producers: ["Lawrence Bender"],
        date: "19/08/2009",
        image: "http://fr.web.img2.acsta.net/r_1920_1080/medias/nmedia/18/70/45/22/19123474.jpg",
        language: "english",
        rating: 4.3,
        tags: ["adventure","drama","war","999"]
    },
    {
        title: "The conjuring",
        description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        duration: 112,
        types: ["horror","mystery","thriller"],
        actors: ["Patrick Wilson","Vera Farmiga","Ron Livingston"],
        directors: ["James Wan"],
        producers: ["Tony DeRosa-Grund","Peter Safran","Rob Cowan"],
        date: "21/08/2013",
        image: "http://fr.web.img6.acsta.net/r_1920_1080/pictures/210/025/21002526_20130430172022533.jpg",
        language: "english",
        rating: 4.2,
        tags: ["horror","mystery","thriller","halloween","120"]
    },
    {
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        description: "Four kids travel through a wardrobe to the land of Narnia and learn of their destiny to free it with the guidance of a mystical lion.",
        duration: 143,
        types: ["adventure","family","fantasy"],
        actors: ["Tilda Swinton","Georgie Henley","William Moseley"],
        directors: ["Andrew Adamson"],
        producers: ["Mark Johnson","Philip Steue"],
        date: "21/12/2005",
        image: "http://fr.web.img2.acsta.net/r_1920_1080/medias/nmedia/18/35/53/32/18463695.jpg",
        language: "english",
        rating: 3.5,
        tags: ["adventure","family","fantasy","999"]
    },
    {
        title: "Crazy Rich Asians",
        description: "This contemporary romantic comedy, based on a global bestseller, follows native New Yorker Rachel Chu to Singapore to meet her boyfriend's family.",
        duration: 120,
        types: ["comedy","drama","romance"],
        actors: ["Constance Wu","Henry Golding","Michelle Yeoh"],
        directors: ["Jon M. Chu"],
        producers: ["Nina Jacobson","Brad Simpson","John Penotti"],
        date: "07/11/2018",
        image: "http://fr.web.img3.acsta.net/r_1920_1080/pictures/18/09/17/15/47/3771769.jpg",
        language: "english",
        rating: 3.3,
        tags: ["comedy","drama","romance","valentine's day","120"]
    },
    {
        title: "The Fifth Element",
        description: "In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr. Zorg at bay.",
        duration: 126,
        types: ["action","adventure","sci-fi"],
        actors: ["Bruce Willis","Milla Jovovich","Gary Oldman"],
        directors: ["Luc Besson"],
        producers: ["Patrice Ledoux"],
        date: "07/05/1997",
        image: "https://m.media-amazon.com/images/M/MV5BZWFjYmZmZGQtYzg4YS00ZGE5LTgwYzAtZmQwZjQ2NDliMGVmXkEyXkFqcGdeQXVyNTUyMzE4Mzg@._V1_SY1000_CR0,0,696,1000_AL_.jpg",
        language: "english",
        rating: 4.2,
        tags: ["action","adventure","sci-fi","120"]
    },
    {
        title: "Home Alone",
        description: "An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.",
        duration: 103,
        types: ["comedy","family"],
        actors: ["Macaulay Culkin","Joe Pesci","Daniel Stern"],
        directors: ["Chris Columbus"],
        producers: ["John Hughes"],
        date: "19/12/1990",
        image: "http://fr.web.img5.acsta.net/r_1920_1080/pictures/17/11/15/15/14/4627669.jpg",
        language: "english",
        rating: 3.3,
        tags: ["comedy","family","christmas","120"]
    },
    {
        title: "Valentine's Day",
        description: "Intertwining couples and singles in Los Angeles break-up and make-up based on the pressures and expectations of Valentine's Day.",
        duration: 125,
        types: ["comedy","romance"],
        actors: ["Julia Roberts","Jessica Alba","Anne Hathaway","Ashton Kutcher","Bradley Cooper","Patrick Dempsey"],
        directors: ["Garry Marshall"],
        producers: ["Mike Karz","Wayne Allan Rice"],
        date: "17/02/2019",
        image: "http://fr.web.img3.acsta.net/r_1920_1080/medias/nmedia/18/73/64/49/19227040.jpg",
        language: "english",
        rating: 2.6,
        tags: ["comedy","romance","valentine's day","120"]
    }
];